version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
    volumes:
      - .:/app
    networks:
      - my_network
    command: python app.py

  db:
    image: postgres:15
    container_name: my_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
